# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d880b2cd844f30c71aa4be073bf4e0f2b0776b83800df6a3ebbe0e4457e3d6b542b8630c9c088778470aec0d9f6200a2fda4542183360c3f7ac957a240a595d

test:
  secret_key_base: 2258df15c57bfcbc7f53e393b092d349d5869f561de8d744d48262c1c9fb99c612d4adb1455433fcb12581e69e5cf6f8325a27d804ee196db1509be7fe9ccc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
